run test-reporter in separate workflow

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -2,21 +2,9 @@ name: .NET
 
 on:
   push:
-    branches: 
-      - 'master'
-      - 'develop'
-      - 'feature/*'
-      - 'hotfix/*'
-      - 'release/*'
-      
+    branches: [ master, develop, feature/*, hotfix/*, release/* ]
   pull_request:
-    branches: 
-      - 'master'
-      - 'develop'
-      - 'feature/*'
-      - 'hotfix/*'
-      - 'release/*'
-      - '!dependabot/*'
+    branches: [ master, develop, feature/*, hotfix/*, release/* ]
 
 jobs:
   build:
@@ -33,12 +21,10 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-build --verbosity normal
-    - name: Test Reporter
-      uses: dorny/test-reporter@v1.4.2
-      if: success() || failure()
-      with: 
-        name: Tests
-        path: 'tests/**/*.trx'
-        reporter: dotnet-trx
-        fail-on-error: true
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()      # run this step even if previous step failed
+        with:
+          name: test-results
+          path: 'tests/**/*.trx'
 
